# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'slider.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(90, 220, 611, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Slider_63 = QtWidgets.QSlider(self.gridLayoutWidget)
        self.Slider_63.setOrientation(QtCore.Qt.Vertical)
        self.Slider_63.setObjectName("Slider_63")
        self.gridLayout.addWidget(self.Slider_63, 0, 1, 1, 1)
        self.Slider_250 = QtWidgets.QSlider(self.gridLayoutWidget)
        self.Slider_250.setOrientation(QtCore.Qt.Vertical)
        self.Slider_250.setObjectName("Slider_250")
        self.gridLayout.addWidget(self.Slider_250, 0, 3, 1, 1)
        self.Slider_1000 = QtWidgets.QSlider(self.gridLayoutWidget)
        self.Slider_1000.setOrientation(QtCore.Qt.Vertical)
        self.Slider_1000.setObjectName("Slider_1000")
        self.gridLayout.addWidget(self.Slider_1000, 0, 5, 1, 1)
        self.Slider_2000 = QtWidgets.QSlider(self.gridLayoutWidget)
        self.Slider_2000.setOrientation(QtCore.Qt.Vertical)
        self.Slider_2000.setObjectName("Slider_2000")
        self.gridLayout.addWidget(self.Slider_2000, 0, 6, 1, 1)
        self.Slider_125 = QtWidgets.QSlider(self.gridLayoutWidget)
        self.Slider_125.setOrientation(QtCore.Qt.Vertical)
        self.Slider_125.setObjectName("Slider_125")
        self.gridLayout.addWidget(self.Slider_125, 0, 2, 1, 1)
        self.Slider_16000 = QtWidgets.QSlider(self.gridLayoutWidget)
        self.Slider_16000.setOrientation(QtCore.Qt.Vertical)
        self.Slider_16000.setObjectName("Slider_16000")
        self.gridLayout.addWidget(self.Slider_16000, 0, 9, 1, 1)
        self.Slider_4000 = QtWidgets.QSlider(self.gridLayoutWidget)
        self.Slider_4000.setOrientation(QtCore.Qt.Vertical)
        self.Slider_4000.setObjectName("Slider_4000")
        self.gridLayout.addWidget(self.Slider_4000, 0, 7, 1, 1)
        self.Slider_31 = QtWidgets.QSlider(self.gridLayoutWidget)
        self.Slider_31.setOrientation(QtCore.Qt.Vertical)
        self.Slider_31.setObjectName("Slider_31")
        self.gridLayout.addWidget(self.Slider_31, 0, 0, 1, 1)
        self.Slider_8000 = QtWidgets.QSlider(self.gridLayoutWidget)
        self.Slider_8000.setOrientation(QtCore.Qt.Vertical)
        self.Slider_8000.setObjectName("Slider_8000")
        self.gridLayout.addWidget(self.Slider_8000, 0, 8, 1, 1)
        self.Slider_500 = QtWidgets.QSlider(self.gridLayoutWidget)
        self.Slider_500.setOrientation(QtCore.Qt.Vertical)
        self.Slider_500.setObjectName("Slider_500")
        self.gridLayout.addWidget(self.Slider_500, 0, 4, 1, 1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
